/*!
 * \file        sccp_cli_table.h
 * \brief       SCCP CLI Table Macro Header
 * \author      Diederik de Groot <ddegroot [at] users.sf.net>
 * \note        This program is free software and may be modified and distributed under the terms of the GNU Public License.
 *              See the LICENSE file at the top of the source tree.
 *
 */
#ifndef DOXYGEN_SHOULD_SKIP_THIS

#ifndef _CLI_AMI_TABLE_INCLUDE
#define _CLI_AMI_TABLE_INCLUDE

#define _CLI_AMI_TABLE_LIST_LOCK(...) CLI_AMI_TABLE_LIST_LOCK(__VA_ARGS__)
#define _CLI_AMI_TABLE_LIST_ITERATOR(...) CLI_AMI_TABLE_LIST_ITERATOR(__VA_ARGS__)
#define _CLI_AMI_TABLE_LIST_UNLOCK(...) CLI_AMI_TABLE_LIST_UNLOCK(__VA_ARGS__)

#define MERGE2_(_a,_b) _a##_b
#define UNIQUE_VAR(_a,_b) MERGE2_(_a,_b)

#		define AMI_OUTPUT_PARAM(param, width, fmt, ...)                               \
			{                                                                      \
				char camelParam[width + 1];                                    \
				CLI_AMI_CAMEL_PARAM (param, camelParam);                       \
				astman_append (s, "%s: " fmt "\r\n", camelParam, __VA_ARGS__); \
				local_line_total++;                                            \
			}
#endif

// =========== Code To be generated by include file ===============
#ifdef CLI_AMI_TABLE_LIST_ITER_TYPE
CLI_AMI_TABLE_LIST_ITER_TYPE *CLI_AMI_TABLE_LIST_ITER_VAR = NULL;
#endif

#ifndef CLI_AMI_TABLE_BEFORE_ITERATION
#define CLI_AMI_TABLE_BEFORE_ITERATION
#endif
#ifndef CLI_AMI_TABLE_AFTER_ITERATION
#define CLI_AMI_TABLE_AFTER_ITERATION
#endif

/* print headers */
int UNIQUE_VAR(table_entries_, CLI_AMI_TABLE_NAME) = 0;
const char * UNIQUE_VAR(id_, CLI_AMI_TABLE_NAME)            = s && m ? astman_get_header(m, "ActionID") : "";
char         UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME)[256];
if (!sccp_strlen_zero(UNIQUE_VAR(id_, CLI_AMI_TABLE_NAME))) {
	snprintf(UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME), sizeof(UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME)), "ActionID: %s\r\n", UNIQUE_VAR(id_, CLI_AMI_TABLE_NAME));
} else {
	UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME)[0] = '\0';
}
#	define astman_append_inc(...)                                                                                                                                                                                          \
		({                                                                                                                                                                                                              \
			astman_append(__VA_ARGS__);                                                                                                                                                                             \
			local_line_total++;                                                                                                                                                                                     \
		})

char UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME)[256];
snprintf(UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME), sizeof(UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME)), "Event: SCCP%sEntry\r\n", STRINGIFY(CLI_AMI_TABLE_PER_ENTRY_NAME));

// CLI_AMI_TABLE_FIELD_NAMED(_a, _label, ...) is CLI_AMI_TABLE_FIELD with one extra arg: a
// separate human-readable CLI column label. Use it when the clearest label needs a space
// or other character a bare C identifier can't contain (e.g. "IP Address"); for anything
// that reads fine as a single word, just name the field that directly and skip it.
#define CLI_AMI_TABLE_FIELD(_a,_b,_c,_d,_e) #_a,
#define CLI_AMI_TABLE_FIELD_NAMED(_a,_label,_b,_c,_d,_e) _label,
#define CLI_AMI_TABLE_UTF8_FIELD(_a,_b,_c,_d,_e) CLI_AMI_TABLE_FIELD(_a,_b,_c,_d,_e)
#define CLI_AMI_TABLE_UTF8_FIELD_NAMED(_a,_label,_b,_c,_d,_e) CLI_AMI_TABLE_FIELD_NAMED(_a,_label,_b,_c,_d,_e)
const char *const UNIQUE_VAR(headers_, CLI_AMI_TABLE_NAME)[] = { CLI_AMI_TABLE_FIELDS };
sccp_cli_table_data_t UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME) = {
    .headers = UNIQUE_VAR(headers_, CLI_AMI_TABLE_NAME),
    .columns = ARRAY_LEN(UNIQUE_VAR(headers_, CLI_AMI_TABLE_NAME)),
};
#undef CLI_AMI_TABLE_FIELD
#undef CLI_AMI_TABLE_FIELD_NAMED
#undef CLI_AMI_TABLE_UTF8_FIELD
#undef CLI_AMI_TABLE_UTF8_FIELD_NAMED
if (s) {
	astman_append_inc(s, "Event: TableStart\r\n");
	astman_append_inc(s, "TableName: %s\r\n", STRINGIFY(CLI_AMI_TABLE_NAME));
	if (s && m && sccp_strcaseequals(astman_get_header(m, "TableFormatVersion"), "2")) {
		snprintf(UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME), sizeof(UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME)), "Event: %s_Entry\r\n", STRINGIFY(CLI_AMI_TABLE_PER_ENTRY_NAME));
		astman_append_inc(s, "TableFormatVersion: %s\r\n", "2");
	}
	astman_append_inc(s, "%s\r\n", UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME));
	local_line_total++;
}

	/* iterator through list */
if (!s) {
#define CLI_TABLE_CELL_s(_b,_e) { const char *cell_text = (_e); sccp_cli_table_add(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), "%s", cell_text ? cell_text : "--"); }
#define CLI_TABLE_CELL_d(_b,_e) sccp_cli_table_add(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), "%d", _e);
#define CLI_TABLE_CELL_p(_b,_e) sccp_cli_table_add(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), "%p", (void *)(_e));
#define CLI_TABLE_CELL_f(_b,_e) sccp_cli_table_add(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), "%f", (double)(_e));
#define CLI_AMI_TABLE_FIELD(_a,_b,_c,_d,_e) CLI_TABLE_CELL_##_c(_b,_e)
#define CLI_AMI_TABLE_FIELD_NAMED(_a,_label,_b,_c,_d,_e) CLI_AMI_TABLE_FIELD(_a,_b,_c,_d,_e)
#define CLI_AMI_TABLE_UTF8_FIELD(_a,_b,_c,_d,_e) CLI_AMI_TABLE_FIELD(_a,_b,_c,_d,_e)
#define CLI_AMI_TABLE_UTF8_FIELD_NAMED(_a,_label,_b,_c,_d,_e) CLI_AMI_TABLE_UTF8_FIELD(_a,_b,_c,_d,_e)
#ifdef CLI_AMI_TABLE_LIST_ITERATOR
	_CLI_AMI_TABLE_LIST_LOCK(CLI_AMI_TABLE_LIST_ITER_HEAD);
	_CLI_AMI_TABLE_LIST_ITERATOR(CLI_AMI_TABLE_LIST_ITER_HEAD, CLI_AMI_TABLE_LIST_ITER_VAR, list) {
#else
	CLI_AMI_TABLE_ITERATOR {
#endif
		CLI_AMI_TABLE_BEFORE_ITERATION
		CLI_AMI_TABLE_FIELDS
	CLI_AMI_TABLE_AFTER_ITERATION}
#ifdef CLI_AMI_TABLE_LIST_ITERATOR
	_CLI_AMI_TABLE_LIST_UNLOCK(CLI_AMI_TABLE_LIST_ITER_HEAD);
#endif
#undef CLI_AMI_TABLE_FIELD
#undef CLI_AMI_TABLE_FIELD_NAMED
#undef CLI_AMI_TABLE_UTF8_FIELD
#undef CLI_AMI_TABLE_UTF8_FIELD_NAMED
} else {
#	define CLI_AMI_TABLE_FIELD1(_paramstr, _fmtstr, _vargs)        CLI_AMI_OUTPUT_PARAM(_paramstr, 0, _fmtstr, _vargs);
#	define CLI_AMI_TABLE_FIELD(_param, _width, _fmt, _len, _vargs) CLI_AMI_TABLE_FIELD1(#        _param, "%" #        _fmt, _vargs)
#	define CLI_AMI_TABLE_FIELD_NAMED(_param, _label, _width, _fmt, _len, _vargs) CLI_AMI_TABLE_FIELD(_param, _width, _fmt, _len, _vargs)
#	define CLI_AMI_TABLE_UTF8_FIELD(_param, _width, _fmt, _len, _vargs) CLI_AMI_TABLE_FIELD(_param, _width, _fmt, _len, _vargs)
#	define CLI_AMI_TABLE_UTF8_FIELD_NAMED(_param, _label, _width, _fmt, _len, _vargs) CLI_AMI_TABLE_FIELD(_param, _width, _fmt, _len, _vargs)
#	ifdef CLI_AMI_TABLE_LIST_ITERATOR
	_CLI_AMI_TABLE_LIST_LOCK(CLI_AMI_TABLE_LIST_ITER_HEAD);
	_CLI_AMI_TABLE_LIST_ITERATOR(CLI_AMI_TABLE_LIST_ITER_HEAD, CLI_AMI_TABLE_LIST_ITER_VAR, list) {
#else
	CLI_AMI_TABLE_ITERATOR {
#endif
		CLI_AMI_TABLE_BEFORE_ITERATION
		UNIQUE_VAR(table_entries_, CLI_AMI_TABLE_NAME)++;
		astman_append_inc(s, "%s", UNIQUE_VAR(eventText_, CLI_AMI_TABLE_NAME));

		astman_append_inc(s, "ChannelType: SCCP\r\n");
		astman_append_inc(s, "ChannelObjectType: %s\r\n", STRINGIFY(CLI_AMI_TABLE_PER_ENTRY_NAME));
		CLI_AMI_TABLE_FIELDS
		astman_append_inc(s, "%s\r\n", UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME));
		local_line_total++;
		CLI_AMI_TABLE_AFTER_ITERATION
	}
#ifdef CLI_AMI_TABLE_LIST_ITERATOR
	_CLI_AMI_TABLE_LIST_UNLOCK(CLI_AMI_TABLE_LIST_ITER_HEAD);
#endif
#	undef CLI_AMI_TABLE_FIELD1
#	undef CLI_AMI_TABLE_FIELD
#	undef CLI_AMI_TABLE_FIELD_NAMED
#	undef CLI_AMI_TABLE_UTF8_FIELD
#	undef CLI_AMI_TABLE_UTF8_FIELD_NAMED
}

	/* print footer */
if (!s) {
#ifdef CLI_AMI_TABLE_TITLE
    sccp_cli_table_print(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), fd, CLI_AMI_TABLE_TITLE);
#else
    sccp_cli_table_print(&UNIQUE_VAR(table_, CLI_AMI_TABLE_NAME), fd, STRINGIFY(CLI_AMI_TABLE_NAME));
#endif
} else {
	astman_append_inc(s, "Event: TableEnd\r\n");
	astman_append_inc(s, "TableName: %s\r\n", STRINGIFY(CLI_AMI_TABLE_NAME));
	astman_append_inc(s, "TableEntries: %d\r\n", UNIQUE_VAR(table_entries_, CLI_AMI_TABLE_NAME));
	astman_append_inc(s, "%s\r\n", UNIQUE_VAR(idText_, CLI_AMI_TABLE_NAME));
	local_line_total++;
}

#ifdef CLI_AMI_TABLE_NAME
#undef CLI_AMI_TABLE_NAME
#endif

#ifdef CLI_AMI_TABLE_PER_ENTRY_NAME
#undef CLI_AMI_TABLE_PER_ENTRY_NAME
#endif

#ifdef CLI_AMI_TABLE_LIST_ITER_TYPE
#undef CLI_AMI_TABLE_LIST_ITER_TYPE
#endif

#ifdef CLI_AMI_TABLE_LIST_ITER_VAR
#undef CLI_AMI_TABLE_LIST_ITER_VAR
#endif

#ifdef CLI_AMI_TABLE_LIST_ITER_HEAD
#undef CLI_AMI_TABLE_LIST_ITER_HEAD
#endif

#ifdef CLI_AMI_TABLE_LIST_LOCK
#undef CLI_AMI_TABLE_LIST_LOCK
#endif

#ifdef CLI_AMI_TABLE_LIST_ITERATOR
#undef CLI_AMI_TABLE_LIST_ITERATOR
#endif

#ifdef CLI_AMI_TABLE_ITERATOR
#undef CLI_AMI_TABLE_ITERATOR
#endif

#ifdef CLI_AMI_TABLE_BEFORE_ITERATION
#undef CLI_AMI_TABLE_BEFORE_ITERATION
#endif

#ifdef CLI_AMI_TABLE_AFTER_ITERATION
#undef CLI_AMI_TABLE_AFTER_ITERATION
#endif

#ifdef CLI_AMI_TABLE_LIST_UNLOCK
#undef CLI_AMI_TABLE_LIST_UNLOCK
#endif

#ifdef CLI_AMI_TABLE_FIELDS
#undef CLI_AMI_TABLE_FIELDS
#endif
	// =========== End of Code To be generated by include file ============
#endif														/* DOXYGEN_SHOULD_SKIP_THIS */
// kate: indent-width 8; replace-tabs off; indent-mode cstyle; auto-insert-doxygen on; line-numbers on; tab-indents on; keep-extra-spaces off; auto-brackets off;

#undef CLI_TABLE_CELL_s
#undef CLI_TABLE_CELL_d
#undef CLI_TABLE_CELL_p
#undef CLI_TABLE_CELL_f
#undef CLI_AMI_TABLE_TITLE
